### ISSUE TITLE
[Proposal] Consider using Eigen C++ library for math

### ISSUE THREAD

**Issue by mxgrey** [vsg-dev/VulkanSceneGraphPrototype#47]
**Is your feature request related to a problem? Please describe.**
After working on a variety of projects in the past which each implement their own custom math types, I've repeatedly seen the pitfalls of developing and maintaining a custom internal math library, even when it's expected that only relatively simple math types will be needed.

For one, it's hard to anticipate the scope that will be needed from the math infrastructure. It's easy to think that for something like graphics you really just need some simple matrix arithmetic, which is just some for-loops; in the worst case, those for-loops are nested. But then what if you want to add more sophisticated features down the road? Maybe some awesome new graphics algorithm requires singular value decomposition? You may find yourself adding arbitrarily more features which then need to be maintained.

And anticipating the scope of features needed by end-users is even harder. When your custom math library is inadequate for the needs of end-users, they're put in a position where they need to either implement all sorts of difficult math on top of your custom math library, or else convert data back and forth between yours and a math library that does what they need.

**Describe the solution you'd like**
I would propose using the [Eigen C++ math library](http://eigen.tuxfamily.org/index.php?title=Main_Page). It's an extremely powerful, versatile, feature-rich, fast, and efficient C++ FOSS math library.

Eigen is licensed under MPL which means it's free to use with the only restriction being that changes to Eigen source files must be shared. I believe that VSG and its downstream users would not require any modifications to Eigen at any time, so Eigen's license would not have any impact.

Eigen is supported and distributed across all major platforms, so adding it as a dependency should be trivial. Its header-only files can even be dropped into the VSG project source code, so that the distribution method is never a concern.

I see [here in the design docs](https://vsg-dev.github.io/VulkanSceneGraphPrototype/include/vsg/maths/) the design motivations of the math library seem to be:

1. API that resembles GSLS
2. Memory storage that aligns with Vulkan types

Regarding (1), admittedly Eigen's data types don't have an identical API to the GLSL types. Instead of `vec.x`, in Eigen you'd need to do `vec.x()`. Basically, the API is the same, except Eigen's named component accessors are functions instead of using unions. But other than needing to add parentheses, the Eigen API is a superset of the GLSL API. To get class names like `vec3`, `ivec2`, it would be easy to assign C++ aliases to the Eigen data types.

Regarding (2), all the Eigen Vector/Matrix types provides a `.data()` member function that returns a pointer to an array whose memory layout is (I believe) the same as what Vulkan buffers would use (although I can investigate this more if necessary). Eigen also provides an extremely versatile [Map](https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html) class which is great at converting between different representations of vector/matrix layouts. Even if `.data()` is insufficient, the `Map` class will easily be able to handle any conversions necessary (including any conversions that end-users might want to do to convert VSG data into their own math library's representation).

**Describe alternatives you've considered**
Admittedly I may be biased towards Eigen because I'm extremely familiar with it after using it heavily for ~8 years now, but I have only good things to say about it.

Other math libraries may be worth considering, like [Blaze](https://bitbucket.org/blaze-lib/blaze), but I can't speak to any of those other options personally.

**Additional context**
If there's any inclination to consider using Eigen in VSG, I'd be perfectly happy to hammer through the source code and replace the existing use of the custom math objects with Eigen data types to illustrate what the change would look like. I wouldn't be offended if those changes ultimately get rejected and you decide to stick with the custom math types; I'll gladly do it anyway if it would help to make a decision one way or the other.

**Comment by vsg-dev** [comment]
During the early stages I considered using 3rd party libs for maths and decided against it.  Providing a coherent single library focused on the needs of a scene graph is core to the VSG project, this can't be achieving this by pulling together disparate libraries that have their own conventions. 

In the case of maths support, the VSG already has many of the required classes already written that are working well, they are consistent with GLSL and Vulkan.  The task of writing and maintaining them is minimal.

If users want to use other 3rd party maths libs then the best we can do is make it easy for them to adapt between the them when it's required.  This might simply be a case of members of the community writing small adapter code and provide a example of using them together.  Such an approach scales to any number of 3rd party libs, so whether it be Eigen or GLM is the lib you know it can still be used alongside the VSG.
